name: Python CI

on:
  push:
    branches: [ "main" ] # Adjust if your main branch is different
  pull_request:
    branches: [ "main" ] # Adjust if your main branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Specify Python versions to test against

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install . # Install the base12math package itself
    - name: Test with pytest
      run: |
        pytest tests/ # Run tests specifically from the tests directory
